# Generated by Django 5.1 on 2024-08-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news_product_image_cart_cartitem_newscomment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
