# Generated by Django 5.1 on 2024-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_staff_alter_cart_user_alter_like_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
