# Generated by Django 5.2.3 on 2025-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_like_unique_together_like_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('PayPal', 'PayPal'), ('VNPay', 'VNPay')], default='Cash', max_length=20),
        ),
    ]
