# Generated by Django 5.1 on 2025-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_description_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Canceled', 'Canceled'), ('Expired', 'Expired'), ('Refunding', 'Refunding'), ('Refunded', 'Refunded'), ('Chargeback', 'Chargeback')], default='Pending', max_length=20),
        ),
    ]
