# Generated by Django 5.1 on 2025-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_payment_id_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Canceled', 'Canceled'), ('Expired', 'Expired'), ('Refunding', 'Refunding'), ('Refunded', 'Refunded'), ('Chargeback', 'Chargeback')], default='Pending', max_length=20),
        ),
    ]
