# Generated by Django 5.1 on 2025-08-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Số nhà, đường, phường/xã')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tòa nhà, căn hộ (nếu có)')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Mã bưu điện')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='Quốc gia')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('is_billing', models.BooleanField(default=False, verbose_name='Địa chỉ thanh toán')),
                ('is_shipping', models.BooleanField(default=True, verbose_name='Địa chỉ giao hàng')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú giao hàng')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.customer')),
            ],
            options={
                'verbose_name_plural': 'Địa chỉ',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='api.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='api.address'),
        ),
    ]
