# Generated by Django 5.1 on 2025-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customer_phone_customer_point_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_claimed',
            field=models.BooleanField(default=False, help_text='Whether points have been claimed by customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.IntegerField(default=0, help_text='Points earned from this order'),
        ),
    ]
