# Generated by Django 5.1 on 2025-09-14 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_image_product_thumbnail_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique coupon code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Coupon name for admin', max_length=200)),
                ('description', models.TextField(help_text='Coupon description for customers')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount for percentage type', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to use coupon', max_digits=10)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total usage limit (null = unlimited)', null=True)),
                ('usage_limit_per_customer', models.PositiveIntegerField(default=1, help_text='Usage limit per customer')),
                ('valid_from', models.DateTimeField(help_text='Coupon valid from date')),
                ('valid_until', models.DateTimeField(help_text='Coupon expiry date')),
                ('coupon_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('first_time', 'First Time Customer'), ('loyalty', 'Loyalty Reward')], default='public', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Total times this coupon has been used')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total discount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before discount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.coupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_amount', models.DecimalField(decimal_places=2, help_text='Order amount when coupon was used', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount applied', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='api.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='api.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usage', to='api.order')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usage History',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Staff who assigned this coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_customers', to='api.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_coupons', to='api.customer')),
            ],
            options={
                'verbose_name': 'Customer Coupon Assignment',
                'verbose_name_plural': 'Customer Coupon Assignments',
                'unique_together': {('customer', 'coupon')},
            },
        ),
    ]
