# Generated by Django 5.1 on 2025-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_newscategory_alter_news_options_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=100, null=True),
        ),
    ]
