# Generated by Django 5.1 on 2025-09-19 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_news_meta_description_alter_news_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('email', models.EmailField(help_text='Email address where token was sent', max_length=254)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('is_used', models.BooleanField(default=False, help_text='Whether token has been used')),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed attempts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
